<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## Lists

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#Information stored as lists
#Order of each element is important, py_super_names[0] will always be "Black Widow"

## Arrays

In [9]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"]) #()needed as np.array is a function
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])


print(np_super_names[0])
print(np_real_names[0])

Black Widow
Natasha Romanoff


## Dictionary

In [12]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

print(superhero_info["Tony Stark"])
print(superhero_info["Iron Man"]) #"Iron Man" is the element, to access this element, you need to 
                                  # enter the key, which is "Tony Stark" instead

Iron Man


KeyError: 'Iron Man'

In [15]:
superhero_info_arrays = {
    np_real_names: np_super_names
}

print(superhero_info_arrays ["Natasha Romanoff"]) #ok i guess this dosent work

TypeError: unhashable type: 'numpy.ndarray'

In [14]:
superhero_info_list = {
    py_real_names: py_super_names
}

print(superhero_info_list["Natasha Romanoff"]) #ok i will not be lazy

TypeError: unhashable type: 'list'

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [16]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [34]:
print(f"{py_real_names[0]} is {py_super_names[0]}\n") # "Natasha Romanoff", "Black Widow"
print(f"{py_real_names[1]} is {py_super_names[1]}\n") # "Iron Man", "Tony Stark"
print(f"{py_real_names[2]} is {py_super_names[2]}\n") # "Doctor Strange", "Stephen Strange"

print("Using negative index:\n")                                           # reverse indexing,
print(f"{py_super_names[-1]}, {py_super_names[-2]}, {py_super_names[-3]}") # "Doctor Strange" = [-1]

Natasha Romanoff is Black Widow

Tony Stark is Iron Man

Stephen Strange is Doctor Strange

Using negative index:

Doctor Strange, Iron Man, Black Widow


## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

print(superhero_info["Tony Stark"])
print(superhero_info.keys())        
print(superhero_info.values())

Iron Man
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


In [42]:
print(superhero_info.keys())  #() needed as .keys is a function for the dictionary "superhero_info"
print(superhero_info.values())

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


## 1.4 Higher dimensional lists

In [48]:
py_superhero_info = [["Natasha Romanoff","Black Widow",],
                     ["Tony Stark","Iron Man"],
                    ["Stephen Strange", "Doctor Strange"]]

print(py_superhero_info[1][1])
print(py_superhero_info[0][1])   #prints specific element in the list
print(py_superhero_info[1])      #prints the 2nd element altogether in the first "outer" list

Iron Man
Black Widow
['Tony Stark', 'Iron Man']


# 2 Lists vs. Arrays

In [3]:
py_list_2d = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],       #Defines a Python list
              [5,"E"],[6,"F"],[7,"G"], [8,"H"],
              [9,"I"], [10,"J"]]

np_array_2d = np.array(py_list_2d)                   #Make the python list into a NumPy Array

## 2.1 Size

In [62]:
print(f"The number of elements in the list 'py_list_2d' is {len(py_list_2d)}")       #length of the pylist, number of elements
print(f"The number of elements in the array 'np_array_2d' is {len(np_array_2d)}")


np_array_2d.shape   #10 elements each element contain 2 sub elements

The number of elements in the list 'py_list_2d' is 14
The number of elements in the array 'np_array_2d' is 10


(10, 2)

In [6]:
py_list_2d.append([11,"J","Trial"])

print(len(py_list_2d))
np_array_2d = np.array(py_list_2d) #Array has to be all of the same shape
print(np_array_2d.shape)   #help why does it not recognise and count the last added element

13


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (13,) + inhomogeneous part.

## 2.2 Arrays are fussy about type

In [75]:
py_list = [1, 1.5, "A"]
np_array = np.array(py_list)

#type of element in a python list
print(py_list)
print(f"The first element is {type(py_list[0])}")
print(f"The second element is {type(py_list[1])}")
print(f"The third element is {type(py_list[2])}")

#type of element in a NumPy array
print(np_array)
print(f"The first element is {type(np_array[0])}")
print(f"The second element is {type(np_array[1])}")
print(f"The third element is {type(np_array[2])}")

[1, 1.5, 'A']
The first element is <class 'int'>
The second element is <class 'float'>
The third element is <class 'str'>
['1' '1.5' 'A']
The first element is <class 'numpy.str_'>
The second element is <class 'numpy.str_'>
The third element is <class 'numpy.str_'>


## 2.3 Adding a number

In [78]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)   #reuse the python list
                               #to create a new NumPy array

#Add 10 to each element in py_list 
np_array+=10
print(np_array)

[11 12 13 14 15]


In [79]:
py_list += 10
print(py_list)       #Unable to add 10 to each element individually

TypeError: 'int' object is not iterable

## 2.4 Adding another list

In [80]:
py_list_1 = [1,2,3,4,5]
py_list_2 = [10,20,30,40,50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_3 = py_list_1 + py_list_2             #Append elements in other list into original list
np_array_3 = np_array_1 + np_array_2          #Add each element individually

print(py_list_3)
print(np_array_3)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


In [85]:
test_py_list_1 = [1,2,3,4,5,6]
test_np_array_1 = np.array(test_py_list_1)

test_np_array_2 = np_array_1 + test_np_array_1

print(test_np_array_2)

#number of elements in the array has to be identical

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## 2.5 Multiplying by a Number

In [86]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

py_list *= 3
np_array *= 3

print(py_list)   #repeat each element 3 times
print(np_array)  #Multiply each element in the list by 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


## 2.6 Squaring

In [90]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

np_array **= 2

print(np_array)  #Square each element in the array

[ 1  4  9 16 25]


In [91]:
py_list **= 2
print(py_list)   #python list is unable to do this

TypeError: unsupported operand type(s) for **=: 'list' and 'int'

## 2.7 Asking questions

In [94]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)


#checking if a specific element is present

#Checks the condition in the list but does not speciy it's location
print(f"It is {py_list == 3} that the element 3 is in the python list")

#Checks the condition for every element along the numpy array and tells you it's exact location
print(f"It is {np_array == 3} that the element 3 is in the NumPy Array")   

#checking if a specific element is greater or lower

#Checking each specific element in the array if it is greater than 3
print(f"It is {np_array > 3} that the elements are greater than 3 in the NumPy Array")

It is False that the element 3 is in the python list
It is [False False  True False False] that the element 3 is in the NumPy Array
It is [False False False  True  True] that the elements are greater than 3 in the NumPy Array


In [95]:
#Python list is unable to perform this check
print(f"It is {py_list > 3} that the elements are greater than 3 in the python list")

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [99]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

#Mathematical functions that Python list could perform

print(f"The sum of the elements = {sum(py_list)}")    #Sum of all elements in the list
print(f"The highest element = {max(py_list)}")        #Identify the largest element in the list
print(f"The lowest element = {min(py_list)}\n\n")         #Identify the smallest element in the list
    
#Mathemaical functions that NumPy can perform

print(f"The sum of the elements = {np_array.sum()}")               #Sum of all elements in the list
print(f"The highest element = {np_array.max()}")                   #Maximum value of the element in the list
print(f"The smallest element = {np_array.min()}")                  #Minimum value of the element in the list
print(f"The mean value of the array = {np_array.mean()}")          #Mean value of the elements in the list
print(f"The standard deviation of the array = {np_array.std()}")   #Standard deviation of the elements in the list

The sum of the elements = 15
The highest element = 5
The lowest element = 1


The sum of the elements = 15
The highest element = 5
The smallest element = 1
The mean value of the array = 3.0
The standard deviation of the array = 1.4142135623730951


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes