<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

Subsetting means to select an element from a data set.

**Indexing** means to select a single element from a data set.

**Slicing** means to select a range of elements from a data set.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
        "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

x = py_list
y = np_array

#First element
print("First element:\n")
print(x[0])
print(y[0])

#Last element
print("Last Element:\n")
print(x[-1])
print(y[-1])

#index element 0, 1, 2
print("Element 0 to 2:\n")
print(x[0:3])                         #element 0 and element 3 inclusive
print(y[0:3])

#index element 1,2,3,4,5
print("Element 1 to 5:\n")
print(x[1:6])                         #elment 6 exclusive
print(y[1:6])

#index element 1 to element 5 in intervals of 2
print("Every alternate elements from element 1 to 5:\n")
print(x[1:5:2])
print(y[1:5:2])

#Index element 5 to the end
print("Every element from 5 to the end:\n")
print(x[5:])                          #Element 5 inclusive
print(y[5:])

#Index element 0 to 5
print("Every element from 0 to 5:\n")
print(x[:5])
print(y[:5])                          #Element 0 and 5 inclusive

#Index element 5 to 3 in the reverse order
print("Every element from 5 to 3 in the reverse order:\n")
print(x[3:5:-1])                      #Element 3 and 5 inclusive
print(y[3:5:-1])

#Reverse the list
print("Inverting the elements from the back:\n")
print(x[::-1])
print(y[::-1])

First element:

a1
a1
Last Element:

j10
j10
Element 0 to 2:

['a1', 'b2', 'c3']
['a1' 'b2' 'c3']
Element 1 to 5:

['b2', 'c3', 'd4', 'e5', 'f6']
['b2' 'c3' 'd4' 'e5' 'f6']
Every alternate elements from element 1 to 5:

['b2', 'd4']
['b2' 'd4']
Every element from 5 to the end:

['f6', 'g7', 'h8', 'i9', 'j10']
['f6' 'g7' 'h8' 'i9' 'j10']
Every element from 0 to 5:

['a1', 'b2', 'c3', 'd4', 'e5']
['a1' 'b2' 'c3' 'd4' 'e5']
Every element from 5 to 3 in the reverse order:

[]
[]
Inverting the elements from the back:

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


## 1.2 Arrays only | Subsetting by masking

In [5]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = np_array >3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [6]:
print(np_array[my_mask]) #only print elements that are > 3 aka "true"

[ 4  5  6  7  8  9 10]


**Only works for NumPy arrays**

In [10]:
print(np_array[np_array>3]) #Select elements that are >3 
                            #in the array "np_array"

[ 4  5  6  7  8  9 10]


In [13]:
print(np_array[~(np_array>3)])#~ means "NOT" bitwise Not operator
                              # Elements in np_array that are
                              # NOT more than 3

[1 2 3]


In [15]:
# values that are more than 3 AND less than 8
print(np_array[(np_array > 3) & (np_array < 8)])

[4 5 6 7]


In [14]:
# values that are NOT more than 4, (less than 4)
# OR
# values that are lesser than 6
print(np_array[~(np_array>4) | (np_array < 6)]) # "|" means OR

[1 2 3 4 5]


## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [17]:
py_list_2d = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],
             [5,"E"],[6,"F"],[7,"G"], [8,"H"],
             [9,"I"],[10,"J"]]

np_array_2d = np.array(py_list_2d)

In [19]:
print("The third element of the python list is:\n")
print(py_list_2d[3])

print("The third elment of the NumPy Array:\n")
print(np_array_2d[3])

The third element of the python list is:

[4, 'D']
The third elmeent of the NumPy Array:

['4' 'D']


In [26]:
print("The 4th element in the list and element 0 in the sublist:\n")
print(py_list_2d[3][0])

print("The 3rd element in the list and element 0 in the sublist:\n")
print(np_array_2d[3,0])

The 4th element in the list and element 0 in the sublist:

4
The 3rd element in the list and element 0 in the sublist:

4


In [22]:
print("The first 3 elements of the Python list is:\n")
print(py_list_2d[:3])     #element 0 to element 3 in the list
                          #element 3 inclusive

    
print("The first 3 elements of the NumPy Array is:\n")
print(np_array_2d[:3])    #element 3 exclusive

The first 3 elements of the Python list is:

[[1, 'A'], [2, 'B'], [3, 'C']]
The first 3 elements of the NumPy Array is:

[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [28]:
#provides element 0 in the python list
print(py_list_2d[:3][0])

#Provides the first element of each sublist from 0 to 3
#in the NumPy array

print(np_array_2d[:3, 0])

[1, 'A']
['1' '2' '3']


In [48]:
print(py_list_2d[3:6][0])    #obtains

print(np_array_2d[3:6, 0])   #Excludes element 6,
                             #Returns the first element
                             #in the first 3 elements
        
print(np_array_2d[:, 0])     #All element 0 in all elements in the list

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [46]:
print(py_list_2d[0:6][0])  #obtains the element of (x + y),
                           #in (py_list_2d[x:z][y])

[1, 'A']


## 1.4 Growing lists

In [49]:
#Repeat all the elements in the list 5 times
x = [1,2]*5
print(x)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [54]:
x = [1]            #list called x has the element 1
print(x)

[1]


In [55]:
x = x + [2]        #Add the element "2" into the list
print(x)

[1, 2]


In [56]:
x = x + [3]        #Add the element "3" into the list
print(x)

[1, 2, 3]


In [57]:
x = x + [4]        #Add the element "4" into the list
print(x)

[1, 2, 3, 4]


In [61]:
x = [1]
print(x)

[1]


In [62]:
x += [2]
print(x)

[1, 2]


In [63]:
x += [3]
print(x)

[1, 2, 3]


In [64]:
x += [4]
print(x)

[1, 2, 3, 4]


In [71]:
x = [1]
print(x)

[1]


In [72]:
x.append(2)         #Append function is faster, than the other methods
print(x)

[1, 2]


In [73]:
x.append(3)
print(x)

[1, 2, 3]


In [74]:
x.append(4)
print(x)

[1, 2, 3, 4]


In [75]:
x = [1,2,3]         #List containing elements 1, 2 and 3
x += [4,5,6]        #Add the elements 4, 5 and 6 to the list

print(x)


[1, 2, 3, 4, 5, 6]


In [76]:
x = [1,2,3]
x.extend([4,5,6])    #extend the list with the elements 4,5 and 6

print(x)

[1, 2, 3, 4, 5, 6]


In [77]:
x = [1,2,3]
x.append([4,5,6])   #Append the list and add elments 4,5 and 6
print(x)            #Includes the square brackets as well
                    #Compared to the function extend

[1, 2, 3, [4, 5, 6]]


## 1.5 Tuples

In [78]:
a = (1,2,3)        #Define a tuple
print(a[0])        #Access element 0

1


In [79]:
a[0] += 1

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [82]:
x = [1,2,3]     #Don't do this!
y=x
z=x


[1, 2, 3]
[1, 2, 3]


In [ ]:
x = [1,2,3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes